### ISSUE TITLE
[Icon Request] Pop!_OS icon

### ISSUE THREAD

**Issue by tkashkin** [blackosx/OpenCanopyIcons#1]
Thanks for this great set of consistent icons.

It has all icons I need except [Pop!\_OS](https://pop.system76.com). That's a popular distro and I think its icon might be useful to someone besides me.

Source icon svg: https://github.com/pop-os/icon-theme/blob/master/src/bitmaps/logos/distributor-logo-pop-os.svg

**Comment by blackosx** [comment]
Thanks!

Sure, I can add that icon. Won’t be right away but give me 24 hours. 

Ps. Thanks for your recent pr to Opencore for custom boot entry icons. Nice!

**Comment by blackosx** [comment]
These icons have now been added.
