### ISSUE TITLE
Grey option for Set 2

### ISSUE THREAD

**Issue by Blurayx** [blackosx/OpenCanopyIcons#2]
Are there any plans to add Grey options for set 2?

Added the Manjaro & Windows icons to the blank grey hard drives from set 1 because there are no grey hard drives with Manjaro or Windows icon﻿s in set 2
![upload thumb png 3edd2af7314260a0202d8531f761f40f](https://user-images.githubusercontent.com/2873112/89123525-f6a7e480-d4c7-11ea-9eec-c306adc76b90.png)

**Comment by blackosx** [comment]
Hi. 

I have no current plans to add a grey option for set2. It could possibly be done in the distant future but any free time I currently get is spent working on expanding the range for Set3.
