### ISSUE TITLE
[Icon Request] - KDE Neon

### ISSUE THREAD

**Issue by ghost** [blackosx/OpenCanopyIcons#3]
Hey man, really digging the icon pack! Very clean.

I was hoping you could add an icon for KDE Neon.
I've currently made one myself by replacing the Ubuntu logo with the circular logo for Neon, but it's not quite as clean as I'd like (and I only made the Set 3 Light HDD variant for myself).

An SVG of the logo is available on Wikipedia: https://en.wikipedia.org/wiki/KDE_neon#/media/File:Neon-logo.svg

Kudos again on the icon pack! Super fresh.

**Comment by blackosx** [comment]
Hi. Thanks. Glad you are enjoying them.
KDEneon icons have now been added.
